### ISSUE TITLE
Second time calling stack-up returns S3 error

### ISSUE THREAD

**Issue by dave-lew99** [thestackshack/cim#1]
The second time you run cim stack-up returns an S3 error of the form - 

{
   "message": "Your previous request to create the named bucket succeeded and you already own it.",
   "code": "BucketAlreadyOwnedByYou",
   "region": "eu-west-1",
   "time": "2018-01-18T13:01:02.589Z",
   "requestId": "XXXX",
   "extendedRequestId": "XXXX",
   "statusCode": 409,
   "retryable": false,
   "retryDelay": 53.94489978787147
}

It appears to be the bucket referenced in _cim.yml - if cim is able to create this bucket, deployment works, if it already exists it fails.

The documentation says
"    # Stacks are uploaded here prior to deployment.  The bucket is created if it doesn't exist.
    # The name can be the same for all your _cim.yml files."

**Comment by rgfindl** [comment]
@dave-lew99 Thanks for the bug report.  I just released a fix.
