### ISSUE TITLE
EKS Integration?

### ISSUE THREAD

**Issue by tsal** [thestackshack/cim#5]
I know it just came out, but EKS integration would be nice. My JS is very, very poor, but if I can help somehow, I will.

**Comment by rgfindl** [comment]
Thanks @tsal .  I'm not really sure if/how EKS could be integrated into cim.  EKS has really solid cli utilities like kubectl.  I did create a tutorial and some CloudFormation scripts that spin up an EKS cluster and deploy a service.  You can see it here:  https://hackernoon.com/quickly-spin-up-an-aws-eks-kubernetes-cluster-using-cloudformation-3d59c56b292e

**Comment by tsal** [comment]
@rgfindl - 

Yep! That's what led me here - I just hadn't read all the way through.  It looks like CIM already does everything needed, it's just missing a template - which seems like it might be super-simple. 

I'll go ahead and close this - if I can come up with a PR for the template, I'll do so.  Thanks for the quick response!
